trigger: none

pool:
  name: Hosted VS2017

variables:
  _buildConfiguration: Release
  httpStressProject: 'src/System.Net.Http/tests/StressTests/HttpStress/'
  httpStressArgs: '-maxExecutionTime 20 -displayInterval 60'

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  lfs: false

- task: CmdLine@2
  displayName: Build Corefx
  inputs:
    script: |
      .\build.cmd -ci -configuration $(_buildConfiguration)

- task: PowerShell@2
  displayName: Run HttpStress
  inputs:
    targetType: 'inline'
    script: |
      cd '$(Build.SourcesDirectory)/$(HttpStressProject)'
      # Load testhost sdk in environment
      . .\load-corefx-testhost.ps1 -c $(_buildConfiguration) -b
      # Run the stress suite
      dotnet run -c $(_buildConfiguration) -- $(httpStressArgs)

- task: PublishBuildArtifacts@1
  displayName: Publish Logs
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_buildConfiguration)'
    PublishLocation: Container
    ArtifactName: 'httpstress_$(Agent.Os)_$(Agent.JobName)'
  continueOnError: true
  condition: always()