trigger: none

pool:
  name: Hosted VS2017

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  lfs: false

- task: CmdLine@2
  displayName: Build Corefx
  inputs:
    script: |
      .\build.cmd -ci -configuration $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: Publish Logs
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(buildConfiguration)'
    PublishLocation: Container
    ArtifactName: ${{ 'httpstress_$(Agent.Os)_$(Agent.JobName)' ) }}
  continueOnError: true
  condition: always()