trigger: none

pool:
  name: Hosted VS2017

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true
  fetchDepth: 1
  lfs: false

- task: CmdLine@2
  displayName: Build Corefx
  inputs:
    script: |
      .\build.cmd -configuration $(buildConfiguration)